# Generated by Django 4.2.17 on 2025-01-19 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0007_alter_nation_pkb_alter_nation_active_and_more'),
        ('News', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Nation.nation', verbose_name='Nation'),
        ),
    ]
