# Generated by Django 4.2.17 on 2025-03-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_comment_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='secrecy_roll',
            field=models.IntegerField(default=-1, verbose_name='Secrecy roll'),
        ),
    ]
