# Generated by Django 4.2.17 on 2025-03-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_post_secrecy_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='secrecy_roll_required',
            field=models.BooleanField(default=False, verbose_name='Secrecy roll required'),
        ),
        migrations.AddField(
            model_name='tag',
            name='success_roll_required',
            field=models.BooleanField(default=False, verbose_name='Success roll required'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug url'),
        ),
    ]
