# Generated by Django 4.2.17 on 2025-03-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_tag_secrecy_roll_required_tag_success_roll_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='roll',
        ),
        migrations.AddField(
            model_name='post',
            name='secrecy_roll_override',
            field=models.BooleanField(default=False, verbose_name='Secrecy roll override'),
        ),
        migrations.AddField(
            model_name='post',
            name='success_roll',
            field=models.IntegerField(default=-1, verbose_name='Success roll'),
        ),
        migrations.AddField(
            model_name='post',
            name='success_roll_override',
            field=models.BooleanField(default=False, verbose_name='Success roll override'),
        ),
    ]
