# Generated by Django 4.2.17 on 2025-03-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_remove_post_roll_post_secrecy_roll_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='secrecy_roll_description',
            field=models.TextField(null=True, verbose_name='Secrecy roll description'),
        ),
        migrations.AddField(
            model_name='post',
            name='success_roll_description',
            field=models.TextField(null=True, verbose_name='Success roll description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='secrecy_roll',
            field=models.IntegerField(null=True, verbose_name='Secrecy roll'),
        ),
        migrations.AlterField(
            model_name='post',
            name='secrecy_roll_override',
            field=models.BooleanField(null=True, verbose_name='Secrecy roll override'),
        ),
        migrations.AlterField(
            model_name='post',
            name='success_roll',
            field=models.IntegerField(null=True, verbose_name='Success roll'),
        ),
        migrations.AlterField(
            model_name='post',
            name='success_roll_override',
            field=models.BooleanField(null=True, verbose_name='Success roll override'),
        ),
    ]
