# Generated by Django 4.2.17 on 2025-04-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0013_alter_post_options_alter_post_secrecy_roll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='secrecy_roll',
        ),
        migrations.RemoveField(
            model_name='post',
            name='secrecy_roll_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='success_roll',
        ),
        migrations.RemoveField(
            model_name='post',
            name='success_roll_description',
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(verbose_name='Success roll')),
                ('roll_description', models.TextField(blank=True, null=True, verbose_name='Success roll description')),
                ('roll_type', models.CharField(choices=[('success', 'Success'), ('secrecy', 'Secrecy')], default='success', max_length=255, verbose_name='Roll type')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='News.post', verbose_name='Post')),
            ],
        ),
    ]
