# Generated by Django 4.2.17 on 2025-04-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0014_remove_post_secrecy_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', related_query_name='rolls', to='News.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='roll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Roll value'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='roll_description',
            field=models.TextField(blank=True, null=True, verbose_name='Roll description'),
        ),
    ]
