# Generated by Django 4.2.17 on 2025-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0016_remove_post_is_published_comment_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Was edited'),
        ),
    ]
