# Generated by Django 5.2 on 2025-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0018_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arc',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
