# Generated by Django 4.2.17 on 2025-01-29 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nation', '0009_alter_unit_size_alter_unit_upkeep_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the region')),
                ('region_type', models.CharField(default='planet', max_length=100, verbose_name='Type of region')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('posx', models.PositiveIntegerField(blank=True, null=True, verbose_name='X position')),
                ('posy', models.PositiveIntegerField(blank=True, null=True, verbose_name='Y position')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='Nation.nation', verbose_name='Who this region belongs to')),
            ],
        ),
    ]
