# Generated by Django 4.2.17 on 2025-01-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/photos/uploads/', verbose_name='Image'),
        ),
    ]
