# Generated by Django 4.2.17 on 2025-02-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_alter_region_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='image',
        ),
        migrations.RemoveField(
            model_name='region',
            name='posx',
        ),
        migrations.RemoveField(
            model_name='region',
            name='posy',
        ),
    ]
