# Generated by Django 4.2.17 on 2025-01-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
