# Generated by Django 4.2.17 on 2025-01-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0002_nation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='nation_url'),
        ),
    ]
