# Generated by Django 4.2.17 on 2025-01-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0003_nation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='nation_url'),
        ),
    ]
