# Generated by Django 4.2.17 on 2025-01-18 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nation', '0004_alter_nation_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Armies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='nation',
            name='owner_title',
            field=models.CharField(default='glorious leader', max_length=100),
        ),
        migrations.AlterField(
            model_name='nation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claimed_nations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('size', models.IntegerField()),
                ('upkeep_per_unit', models.IntegerField()),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='Nation.army')),
            ],
            options={
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='army',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armies', to='Nation.nation'),
        ),
    ]
