# Generated by Django 4.2.17 on 2025-01-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0005_army_nation_owner_title_alter_nation_owner_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='slug',
        ),
    ]
