# Generated by Django 4.2.17 on 2025-01-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0006_remove_unit_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='PKB',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nation',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
