# Generated by Django 4.2.17 on 2025-01-19 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0007_alter_nation_pkb_alter_nation_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='army',
            options={'ordering': ['name'], 'verbose_name_plural': 'armies'},
        ),
        migrations.AlterField(
            model_name='army',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armies', to='Nation.nation', verbose_name='allegiance'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='PKB',
            field=models.IntegerField(default=0, verbose_name='PKB'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='population',
            field=models.IntegerField(default=0, verbose_name='Population'),
        ),
    ]
