# Generated by Django 4.2.17 on 2025-01-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0008_alter_army_options_alter_army_nation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='upkeep_per_unit',
            field=models.IntegerField(default=0),
        ),
    ]
