# Generated by Django 4.2.17 on 2025-02-01 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0011_alter_nation_pkb_alter_nation_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='PKB',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='PKB must be greater than 0')], verbose_name='PKB'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='population',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, message='Population must be greater than 0')], verbose_name='Population'),
        ),
    ]
