# Generated by Django 4.2.17 on 2025-02-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0014_alter_army_name_alter_unit_name_alter_unit_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
