# Generated by Django 4.2.17 on 2025-02-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0015_unit_slug_alter_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='slug',
        ),
        migrations.AlterField(
            model_name='army',
            name='name',
            field=models.CharField(default='New army', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(default='New unit', max_length=100, verbose_name='Name'),
        ),
    ]
