# Generated by Django 4.2.17 on 2025-03-26 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nation', '0016_remove_army_slug_remove_unit_slug_alter_army_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='nation',
            name='owner_title',
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_title', models.CharField(default='glorious leader', max_length=100)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_nations', to='Nation.nation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nation',
            name='owners',
            field=models.ManyToManyField(through='Nation.Ownership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.UniqueConstraint(fields=('user', 'nation'), name='unique_ownership'),
        ),
    ]
