# Generated by Django 4.2.17 on 2025-03-26 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nation', '0017_remove_nation_owner_remove_nation_owner_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nation.nation'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_nations', to=settings.AUTH_USER_MODEL),
        ),
    ]
