# Generated by Django 4.2.17 on 2025-03-26 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nation', '0018_alter_ownership_nation_alter_ownership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to=settings.AUTH_USER_MODEL),
        ),
    ]
