# Generated by Django 5.2 on 2025-04-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0019_alter_ownership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='nation',
            name='coat_of_arms',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Coat Of Arms'),
        ),
    ]
