# Generated by Django 5.2 on 2025-04-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nation', '0020_nation_banner_nation_coat_of_arms'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Flag'),
        ),
    ]
